// calculator
export const SET_FIRST_NUMBER = 'SET_FIRST_NUMBER'
export const SET_SECOND_NUMBER = 'SET_SECOND_NUMBER'
export const SET_OPERATION = 'SET_OPERATION'
export const CHANGE_CALCULATION_TYPE = 'CHECK_CALCULATION_TYPE'
export const SET_RESULT = 'SET_RESULT'

// history
export const FETCH_HISTORY_START = 'FETCH_HISTORY_START'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const DELETE_HISTORY = 'DELETE_HISTORY'
